import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/navbar";
import useWallet from "@/hooks/wallet";
import dynamic from "next/dynamic";
import React, { useState } from "react";

const DepositToken = dynamic(() => import("@/components/deposit-token"));
const WithdrawToken = dynamic(() => import("@/components/withdraw-token"));
const AddReward = dynamic(() => import("@/components/add-reward"));

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { connect } = useWallet();
  connect();

  const [activeComponentIndex, setActiveComponentIndex] = useState(0);
  const components = [DepositToken, WithdrawToken, AddReward];

  const cards = [
    { title: "Deposit", desc: "Deposit ERC20 token and get rewards", associatedComponentIndex: 0 },
    { title: "Withdraw", desc: "Withdraw holded ERC20 token", associatedComponentIndex: 1 },
    { title: "Add Reward", desc: "Fund contract with rewards", associatedComponentIndex: 2 },
  ];

  function handleClick(index) {
    setActiveComponentIndex(index);
  }

  return (
    <>
      <Head>
        <title>Staking app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />

        <div className={styles.center}>{React.createElement(components[activeComponentIndex])}</div>

        <div className={styles.grid}>
          {cards.map((card, i) => (
            <a key={i} className={styles.card} onClick={() => handleClick(card.associatedComponentIndex)}>
              <h2 className={inter.className}>
                {card.title} <span>-&gt;</span>
              </h2>
              <p className={inter.className}>{card.desc}</p>
            </a>
          ))}
        </div>
      </main>
    </>
  );
}
